name: time_series_ensembles
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - plotly
  - sktime
  - statsmodels
  - jupyter
  - tqdm
<<<<<<< HEAD
  - python-kaleido
=======
  - kaleido
  - category_encoders
>>>>>>> 0d494b1 (added new notebook for using window lengths)
